blank_issues_enabled: false
contact_links:
  - name: Preguntas generales
    url: https://github.com/CharlieCardenasToledo/penke-ec/discussions
    about: Para preguntas que no son errores ni sugerencias, usa Discussions.
